avast/retdec

README.md

Added apt-get packages

---

scripts/retdec-archive-decompiler.sh
scripts/retdec-config.sh
scripts/retdec-decompiler.sh
scripts/retdec-fileinfo.sh
scripts/retdec-signature-from-library-creator.sh
scripts/retdec-tests-runner.sh
scripts/retdec-unpacker.sh
scripts/retdec-utils.sh
scripts/type_extractor/gen_cstdlib_and_linux_jsons.sh
scripts/type_extractor/gen_windows_and_windrivers_jsons.sh

Issue #258: Replace usage of explicit '#!/bin/bash' with more environmentally friendly '#!/usr/bin/env bash'

---

src/unpackertool/plugins/upx/pe/pe_upx_stub.cpp

Since section names in PE files have a fixed size of 8 bytes, it is fine to have a name without a terminating null byte. Thus, replace `strncpy()` with `memcpy()` to suppress the warning and make the code more readable (we are actually copying bytes, not characters).
Fixes #325.

Improve copying of PE section names in unpacker to suppress GCC 8 warning (#325)

---

src/bin2llvmir/optimizations/globals/global_to_local_and_dead_global_assign.cpp
src/bin2llvmir/optimizations/idioms/idioms.cpp
src/bin2llvmir/optimizations/idioms/idioms_gcc.cpp
src/bin2llvmir/optimizations/param_return/param_return.cpp
src/bin2llvmir/optimizations/syscalls/arm.cpp
src/bin2llvmir/optimizations/syscalls/mips.cpp
src/bin2llvmir/optimizations/unreachable_funcs/unreachable_funcs.cpp
src/bin2llvmir/utils/ir_modifier.cpp

Several fixes for the bin2llvmir project.

Bin2llvmir improvements

---

README.md

Hi there,
Simple PR for the addition of a required dependency.
Thanks,
Pedro

Update README.md to include `libfl-dev` dependency.

---

include/retdec/fileformat/types/dotnet_types/dotnet_class.h
src/fileformat/types/dotnet_types/dotnet_class.cpp
src/fileinfo/file_information/file_information.cpp
src/fileinfo/file_information/file_information.h
src/fileinfo/file_information/file_information_types/dotnet_info.cpp
src/fileinfo/file_information/file_information_types/dotnet_info.h
src/fileinfo/file_presentation/getters/iterative_getter/iterative_distribution_getter/typeref_table_plain_getter.cpp
src/fileinfo/file_presentation/getters/iterative_getter/iterative_subtitle_getter/typeref_table_json_getter.cpp

typeref namespace presentation added

---

deps/yaracpp/CMakeLists.txt

Updating YARA to version 3.9. Want to see if it would pass all tests on all platforms.

Update to YARA 3.9

---

README.md

N -j flag denotes parallel processes

make flag clarification

---

src/fileformat/file_format/pe/pe_format.cpp
src/fileformat/types/resource_table/resource_table.cpp

Also fixed parsing of resources which point to different section.

Fixed reading of version info which has non-matching length of struct and strings

---

include/retdec/cpdetect/compiler_detector/heuristics/pe_heuristics.h
include/retdec/fileformat/file_format/pe/pe_format.h
include/retdec/fileformat/file_format/pe/pe_format_parser/pe_format_parser.h
include/retdec/fileformat/file_format/pe/pe_format_parser/pe_format_parser32.h
include/retdec/fileformat/file_format/pe/pe_format_parser/pe_format_parser64.h
include/retdec/fileformat/file_format/pe/pe_template.h
src/cpdetect/compiler_detector/heuristics/pe_heuristics.cpp
src/fileformat/file_format/pe/pe_format.cpp
src/fileformat/file_format/pe/pe_format_parser/pe_format_parser32.cpp
src/fileformat/file_format/pe/pe_format_parser/pe_format_parser64.cpp

Detection of StarForce, SecuROM and SafeDisc

Detection of StarForce, SecuROM and SafeDisc

---

README.md

Added instructions about direct installation of prebuilt OpenSSL into README

---

src/bin2llvmir/optimizations/decoder/ir_modifications.cpp

Reference: https://github.com/avast/retdec/issues/637

Try to fix issue #637

---

src/bin2llvmir/utils/ir_modifier.cpp

Reference: https://github.com/avast/retdec/issues/636

Try to fix issue #636

---

.appveyor.yml
.travis.yml
CHANGELOG.md
Dockerfile
Dockerfile.dev
README.md
deps/yaramod/CMakeLists.txt
src/pat2yara/modifications.cpp
src/pat2yara/processing.cpp

The new Yaramod does not use Flex and Bison anymore.
This should fix #103.

New yaramod

---

include/retdec/pelib/ImportDirectory.h
include/retdec/pelib/PeLibAux.h
src/pelib/BoundImportDirectory.cpp
src/pelib/IatDirectory.cpp
src/pelib/RelocationsDirectory.cpp

* Check for invalid bound import directory
* Optimization using std::move
* Removed unused structures from PeLibAux.h

* Check for invalid IAT directory

---

src/fileformat/utils/format_detection.cpp
src/pelib/ImageLoader.cpp

…s loader to return ERROR_NONE and loaderError to LDR_ERROR_NTHEADER_OUT_OF_FILE

Fixed issue https://github.com/avast/retdec/issues/921

---

cmake/deps.cmake

Update YARA to a newer version to fix some slow scanning issues that have been fixed in the new version.

Update YARA to 4.2.X

---

include/retdec/common/range.h

Simplify removing range

---

.github/workflows/Linux/build.sh
.github/workflows/Linux/install-deps.sh
.github/workflows/Linux/prepare-clang.sh
.github/workflows/Linux/run-tests.sh
.github/workflows/Windows/build.sh
.github/workflows/Windows/ignore_Debug
.github/workflows/Windows/install-deps.sh
.github/workflows/Windows/prepare-clang.sh
.github/workflows/Windows/run-tests.sh
.github/workflows/common/prepare-retdec-tests.sh
.github/workflows/macOS/build.sh
.github/workflows/macOS/install-deps.sh
.github/workflows/macOS/prepare-clang.sh
.github/workflows/macOS/run-tests.sh
.github/workflows/retdec-ci.yml
doc/doxygen/CMakeLists.txt

This commit provides configuration and support script for running
RetDec build, tests & artifact creation in Github Actions CI.

Continuous integration in Github Actions

---

CHANGELOG.md
cmake/deps.cmake
include/retdec/ctypes/enum_type.h
include/retdec/fileformat/types/dotnet_headers/metadata_header.h
include/retdec/fileformat/types/dotnet_headers/metadata_table.h
include/retdec/fileformat/types/export_table/export.h
include/retdec/fileformat/types/import_table/import.h
include/retdec/fileformat/types/note_section/elf_core.h
include/retdec/fileformat/types/relocation_table/relocation.h
include/retdec/fileformat/types/rich_header/linker_info.h
include/retdec/fileformat/types/rich_header/rich_header.h
include/retdec/fileformat/types/strings/string.h
include/retdec/fileformat/types/tls_info/tls_info.h
include/retdec/fileformat/utils/byte_array_buffer.h
include/retdec/pdbparser/pdb_utils.h
include/retdec/utils/conversion.h
include/retdec/utils/file_io.h
include/retdec/utils/string.h
include/retdec/yaracpp/yara_meta.h
src/fileformat/types/tls_info/tls_info.cpp
src/fileinfo/file_information/file_information_types/elf_core.h
src/pat2yara/logic.h
src/unpackertool/arg_handler.h

Fix https://github.com/avast/retdec/issues/1149.

Fix gcc-13 compilation
