- cmake/install-share.sh
Since install-sh.sh is a part of the install process, we probably don't want to wait for the long default of 15 minutes (https://github.com/chapmanb/bcbio-nextgen/issues/1487).
Was having issues on my build box before applying this change (connections to `*.s3.amazonaws.com` kept hanging).
> Added wget flag to reset connection

- Dockerfile
- Dockerfile.dev
- README.md
`Dockerfile` creates an image from the master branch of this repository. 
`Dockerfile.dev` creates an image from the local repository tree. 
Added instructions to README.md with how to use these containers in a simple use case.
> Add Dockerfiles and instructions for using docker containers

- CITATION
Hello!
This is a copy your 2017 entry on https://retdec.com/publications/ incorporated into the repo as suggested in https://www.software.ac.uk/blog/2013-09-02-encouraging-citation-software-introducing-citation-files. Adding it here may make it simpler for people to cite your software. How about it?
Also, it would be possible edit this PR to:
Cheers!
> expand citability by adding CITATION file

- src/utils/filesystem_path.cpp
Forwarded from https://bugs.debian.org/888067
`realpath` has the ability to allocate buffer itself. This could avoid depending on fix-sized buffer.
> Let realpath allocate a buffer itself

- src/fileformat/file_format/pe/pe_format.cpp
In #87, `fileinfo` crashes are reported when verifying the digital signature of attached PE files. What all the attached files have in common is that we are unable to find a signer or counter-signer for them and `p7->length` is `0`. As the following comment in `pe_format.cpp` suggests, there is no point of continuing in such a case:
```
// If we have no signer and countersigner, there must be something really bad
if(!signerCert && !counterSignerCert)
{
BIO_free(bio);
return;
}
```
Thus, move the signature verification AFTER the check that we have found a signer or a counter-signer. This fixes the signature-verifying crashes for all the files attached to #87.
> Verify digital signature after we have a signer/counter-signer to fix fileinfo crashes

- include/retdec/utils/memory.h
- include/retdec/utils/os.h
- scripts/retdec-decompiler.sh
- src/bin2llvmirtool/bin2llvmir.cpp
- src/fileinfo/fileinfo.cpp
- src/llvmir2hlltool/llvmir2hll.cpp
- src/utils/CMakeLists.txt
- src/utils/memory.cpp
- tests/utils/CMakeLists.txt
- tests/utils/memory_tests.cpp
Adds support for limiting overall memory when running decompilations and tools (#270).
Details:
* Added a new module `memory` into `retdec::utils`, which provides ways of limiting the available memory of the current process. Supported platforms are Windows, Linux, and macOS.
* Added new parameters `--max-memory` and `--max-memory-half-ram` into `retdec-fileinfo`. By default, there is no memory limit when you run the tool.
* Added new parameters `-max-memory` and `-max-memory-half-ram` into `retdec-bin2llvmir` and `retdec-llvmir2hll`. By default, there is no memory limit when you run the tools.
* Added new parameters `--max-memory` and `--no-memory-limit` into `retdec-decompiler.sh` By default, the script limits the memory of the above tools into half of system RAM to prevent potential …
> Add support for limiting overall memory when running decompilations and tools

- deps/llvm/CMakeLists.txt
This was a relict from our old build system, where we built LLVM as an external project from a subdirectory and needed to detect changes in its source files. Now, we build LLVM as an external project from a GitHub URL, so there is no longer a need to re-configure LLVM after it has been built (its sources will never change).
This speeds up the rebuild and installation of RetDec. For example, on my Linux machine, a rebuild without changes has speeded up from
real    0m1.223s
user    0m2.956s
sys     0m1.163s
to
real    0m0.527s
user    0m1.903s
sys     0m0.716s
On Windows, the difference will be even bigger. This lowering of rebuild times is very handy during development.
> Disable forced reconfiguration of LLVM to speed up build and installation

- scripts/retdec-decompiler.sh
When `--cleanup` is used together with `--mode raw`, the input file gets removed (see #309). This PR fixes that by removing the `OUT_RAW_EXECUTABLE` variable from `retdec-decompiler.sh`, which is only set to `$IN` at the beginning of a decompilation and serves no real purpose. It was probably a relict from the past when we supported "raw" decompilations from C source code.
Fixes #309.
> Do not remove the input file when --cleanup is used together with --mode raw (#309)

- scripts/retdec-decompiler.sh
- scripts/retdec-unpacker.sh
- src/unpackertool/unpacker.cpp
This PR adds support for limiting the overall memory of our unpacker (see #290).
Regression tests for this feature were added in https://github.com/avast-tl/retdec-regression-tests/pull/7 (merge the present PR before merging the PR with tests).
> Add support for limiting the overall memory of our unpacker (#290)

- include/retdec/demangler/demtools.h
- include/retdec/utils/file_io.h
- src/demangler/CMakeLists.txt
- src/demangler/demtools.cpp
- src/demangler/gparser.cpp
- src/utils/file_io.cpp
Fix https://github.com/avast-tl/retdec/issues/317 by replacing all `fileExists `method calls with `FilesystemPath::exists()`
> Use FilesystemPath::exists() instead of fileExists() (#317)

- src/config/vtables.cpp
There were identical sub-expressions to the left and to the right of the '==' operator. In other words, vtable item/vtable was compared with itself (that results to 'true') instead of comparison with other vtable item/vtable.
> Fix comparison of vtables and comparison of vtable items.

- src/fileformat/file_format/macho/macho_format.cpp
The symtabCommand method was exited without releasing the 'symbolTable' pointer.
> Fix possible memory leak in MachOFormat::symtabCommand() method.

- CMakeLists.txt
- src/bin2llvmir/optimizations/decoder/ir_modifications.cpp
On macOS there is some warnings about object that has no symbols in it, this is needed to be fixed to make building more clean and clear.
example of build log :
```
[ 94%] Linking CXX static library libretdec-bin2llvmir.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libretdec-bin2llvmir.a(idioms_borland.cpp.o) has no symbols
```
> Eliminate "lib*.a(filexx.cpp.o)" has no symbols on macOS

- src/bin2llvmir/providers/fileimage.cpp
This adds `_CxxThrowException` to the list of terminating functions, which improves quality quite significantly for me (see #397).
> Fix #397 - bin2llvmir: Add more known terminating functions to the list

- src/bin2pat/bin2pat.cpp
As described in https://github.com/avast-tl/retdec/issues/473, `bin2pat` does not die correctly when an error is encountered, which affects the running of other scripts.
> Die as intended on bin2pat error

- src/llvmir2hll/optimizer/optimizers/dead_local_assign_optimizer.cpp
The test for whether a variable is external is loop invariant and only needs to be done once.
It also should fail as early as possible
> DeadLocalAssign repeatedly performs external variable test

- CHANGELOG.md
- scripts/retdec-signature-from-library-creator.py
- src/bin2pat/bin2pat.cpp
The added option -l --list is being used to pass the list of objects
from retdec-signature-from-library-creator.py as a json file.
Resolves #472 
I am uncertain if the change in retdec-bin2pat's help output correctly
follows the Utility Conventions. If it does not, providing a proper
reference would be appreciated.
Regards,
Andrew Strelsky
> Added option -l --list to retdec-bin2pat.

- src/llvmir2hll/graphs/cfg/cfg_traversal.cpp
A lot of recursive stack space is used walking the statements in order, which is not necessary.
> Remove more than half the stack usage of CFG traversal

- CHANGELOG.md
- src/utils/filesystem_path.cpp
Resolves #490 
@metthal I went ahead and implemented your suggestions. I also split it into a separate branch and removed these changes from the other pull request as I should have done in the first place.
Regards,
Andrew Strelsky
> Fixed FilesystemPath::isFile return value.

- include/retdec/llvmir2hll/obtainer/call_info_obtainer.h
- src/llvmir2hll/obtainer/call_info_obtainer.cpp
Previously, the set of sccs was sorted by overall function pointer order.
This was one source of non-determinism.
It also  destroyed the topological ordering of SCCs that tarjan creates.
Also, insertion of each funcset (scc) into the tree of funcsetset possibly compared it against log N funcsets, where each comparison is O(N) (The definition of operator< on sets
performs lexicographic compare on all the members of each set).
This did not do well in the face when inserting large sccs since it may walk a many-thousand member set log N times just to determine the funcset's place in the funcsetset tree.
In practice this is a minor time savings but given we don't want them sorted this way anyway ...
> Change SCC's to be FuncVectorSet instead of FuncSetSet.

- doc/doxygen/CMakeLists.txt
- doc/doxygen/show_doxygen_log.cmake
Currently, you need to check the contents of `build/doc/doxygen/doxygen.log` to see if you caused any warnings/errors in Doxygen documentation. This change shows the contents of the `doxygen.log` file after `make doc` is finished.
> Show doxygen.log contents after doxygen documentation is generated

- src/fileformat/types/dotnet_types/dotnet_type_reconstructor.cpp
https://github.com/avast-tl/retdec/issues/458
I've added a check for null in TypeRef table reconstruction to prevenet null dereference.
> TypeRef table reconstruction SEGFAULT fix

- include/retdec/llvmir2hll/graphs/cfg/cfg_traversal.h
- src/llvmir2hll/graphs/cfg/cfg_traversal.cpp
This removes the rest of the stack usage in the *forward* CFG traversal.
On very large BB testcases i have (millions of BBs), this reduces stack usage to essentially nothing.
This implementation is also somewhat faster for other reasons:
The recursive implementation will touch a lot more nodes due to how it recurses - it will touch each node, start processing the successors, and then recurse on itself (which then processes successors). Depending on CFG structure, when it pops back up, it will now touch a whole bunch of successors that it already processed (it then later discovers it already checked them).
This is fairly bad cache behavior, etc.
This implementation will not, they are cut off before any other processing is done.
It is a minor thing for most CFGs, of course.
I have not …
> Rewrite recursive cfg traversal to non-recursive

- src/fileformat/types/certificate_table/certificate.cpp
Hashes in certificate table changed to lowercase in order to be consistent with other hashes in fileinfo.
> fileformat: Hashes of certificates changed to lowercase

- support/install-yara.py
When you run cmake with `-DRETDEC_COMPILE_YARA=ON` (the default), YARA rules that RetDec uses are compiled during the installation step, which makes decompilations run faster (no need to compile them on the fly during each decompilation). The issue is that YARA rules are compiled sequentially, which takes around 50 seconds to compile them on my machine.
This PR parallelizes their compilation by using all available cores. Now, the compilation takes around 10 seconds on my machine (Intel Xeon E5-1650 @ 3.60GHz, 6 cores with HT = 12 threads).
I have implemented the easy way (using all available cores) as I was unable to find a portable solution of obtaining the value of `-j` (when using `make`) or `/m` (when using Visual Studio).
Implements #540.
> Parallelize compilation of YARA rules during installation (#540)

- scripts/retdec-decompiler.py
The original escaping was flawed (for example, it did not escape backslashes, which caused the produced JSONs to be invalid). The fix is to use [json.dump()](https://docs.python.org/3/library/json.html#json.dump), which properly escapes all the needed characters.
> Fix generation of a log file when calling `retdec-decompiler.py --generate-log`

- deps/pelib/CMakeLists.txt
- include/retdec/fileformat/fftypes.h
- include/retdec/fileformat/file_format/file_format.h
- include/retdec/fileformat/file_format/pe/pe_format.h
- include/retdec/fileformat/file_format/pe/pe_format_parser/pe_format_parser.h
- include/retdec/fileformat/file_format/pe/pe_format_parser/pe_format_parser32.h
- include/retdec/fileformat/file_format/pe/pe_format_parser/pe_format_parser64.h
- include/retdec/fileformat/file_format/pe/pe_template.h
- include/retdec/fileformat/types/tls_info/tls_info.h
- src/fileformat/CMakeLists.txt
- src/fileformat/file_format/file_format.cpp
- src/fileformat/file_format/pe/pe_format.cpp
- src/fileformat/file_format/pe/pe_format_parser/pe_format_parser32.cpp
- src/fileformat/file_format/pe/pe_format_parser/pe_format_parser64.cpp
- src/fileformat/types/resource_table/resource_icon_group.cpp
- src/fileformat/types/tls_info/tls_info.cpp
- src/fileinfo/CMakeLists.txt
- src/fileinfo/file_detector/file_detector.cpp
- src/fileinfo/file_detector/file_detector.h
- src/fileinfo/file_information/file_information.cpp
- src/fileinfo/file_information/file_information.h
- src/fileinfo/file_information/file_information_types/file_information_types.h
- src/fileinfo/file_information/file_information_types/tls_info.cpp
- src/fileinfo/file_information/file_information_types/tls_info.h
- src/fileinfo/file_presentation/getters/iterative_getter/iterative_distribution_getter/tls_info_plain_getter.cpp
- src/fileinfo/file_presentation/getters/iterative_getter/iterative_distribution_getter/tls_info_plain_getter.h
- src/fileinfo/file_presentation/getters/plain_getters.h
- src/fileinfo/file_presentation/json_presentation.cpp
- src/fileinfo/file_presentation/json_presentation.h
- src/fileinfo/file_presentation/plain_presentation.cpp
Thread-local storage information and callback extraction
https://github.com/avast-tl/retdec/issues/417
> TLS parsing and presentation

- deps/llvm/CMakeLists.txt
the dlopen api is part of the libc in OpenBSD and NetBSD.
backtrace api does not belong to the libc in BSD unlike Linux.
> BSD (in general) build fixes.

- include/retdec/fileformat-libdwarf-interface/dwarfdump.add
- include/retdec/fileformat/types/resource_table/bitmap_image.h
- src/capstone2llvmir/arm64/arm64_init.cpp
- src/cpdetect/compiler_detector/elf_compiler.cpp
- src/cpdetect/compiler_detector/heuristics/pe_heuristics.cpp
- src/cpdetect/compiler_detector/macho_compiler.cpp
- src/cpdetect/compiler_detector/raw_data_compiler.cpp
- src/ctypesparser/itanium_ast_ctypes_parser.cpp
- src/demangler/borland_ast/rreference_type.cpp
- src/demangler/borland_ast/type_node.cpp
- src/demangler/context.cpp
- src/fileformat/file_format/pe/pe_format.cpp
- src/getsig/getsig.cpp
- src/stacofin/stacofin.cpp
- tests/demangler/borland_tests.cpp
Hi, a compilation of RetDec outputs warnings considering c-style casts and unused variables in the code. I tried to fix those errors in this PR.
Also, there were some whitespace errors I found in git output that I thought would be great if were fixed too.
> Warning fixes

- src/fileformat/CMakeLists.txt
This should fix debug build of fileinfo in TeamCity with CMake 3.11.0 however this seems to be just a workaround for bug in CMake which is fixed since 3.13.0.
> Temporary fix to fix debug build of fileinfo in TeamCity with CMake 3.11.0

- CHANGELOG.md
- deps/yaracpp/CMakeLists.txt
> deps/yaracpp: update reference to yaracpp version that uses xcrun.

- deps/googletest/CMakeLists.txt
The old reference could not be built with GCC 9.1. Paths to googletests libs changed - update target_link_libraries().
> deps/googletest: update to the latest commit from master.

- deps/openssl/CMakeLists.txt
Without it, RetDec fails to build on some systems, e.g. via our `Dockerfile` that is based on Ubuntu Bionic and does not (at the time of writing) use a pre-built version of OpenSSL:
../../deps/openssl/openssl/src/openssl-install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
Reported in #623.
> Add a missing OpenSSL dependency on Unix: dl

- src/utils/time.cpp
When constructing the empty string, it is better to use `std::string()` (or just `{}` when returning a value) instead of `""` as the latter calls a construct that needs to traverse the empty string literal, which is needless pessimization.
> Improve the return value of utils::timestampToDate()

- include/retdec/bin2llvmir/optimizations/param_return/param_return.h
- include/retdec/bin2llvmir/providers/abi/abi.h
- include/retdec/config/calling_convention.h
- src/bin2llvmir/optimizations/param_return/param_return.cpp
- src/bin2llvmir/providers/abi/abi.cpp
- src/config/calling_convention.cpp
Hi, this PR brings minor modifications into parameter optimization. With these modifications is info about calling conventions (that were used during the parameter analysis) projected into a configuration JSON output file after the optimization.
All architectures with only one calling convention set name of the calling convention to the config as `"arch_default"` (eg. `arm_default`, `mips_default`, etc.).
When it comes to x64, this architecture has two calling conventions that are used on different operating systems. On Windows, calling convention that is used is Microsoft x64. On UNIX like systems, it is System V convention.
For simplicity is therefor name of the convention saved into the config file as `"x64_os_default"`.
Example of `config.json` on x86:
```
{ …
```
> Pass info of used calling conventions into config

- CHANGELOG.md
- src/capstone2llvmir/arm/arm.cpp
- src/capstone2llvmir/arm/arm_impl.h
- src/capstone2llvmir/arm64/arm64.cpp
- src/capstone2llvmir/arm64/arm64_impl.h
- src/capstone2llvmir/capstone2llvmir_impl.cpp
- src/capstone2llvmir/capstone2llvmir_impl.h
- src/capstone2llvmir/mips/mips.cpp
- src/capstone2llvmir/mips/mips_impl.h
- src/capstone2llvmir/powerpc/powerpc.cpp
- src/capstone2llvmir/powerpc/powerpc_impl.h
- src/capstone2llvmir/x86/x86.cpp
- src/capstone2llvmir/x86/x86_impl.h
- tests/capstone2llvmir/CMakeLists.txt
- tests/capstone2llvmir/arm64_tests.cpp
- tests/capstone2llvmir/arm_tests.cpp
- tests/capstone2llvmir/capstone2llvmir_tests.h
- tests/capstone2llvmir/mips_tests.cpp
- tests/capstone2llvmir/powerpc_tests.cpp
- tests/capstone2llvmir/x86_tests.cpp
Redesigns `loadOp` methods that are responsible for the loading of operands of instructions.
Before this PR it was possible to load operands of incompatible type for the instruction which did
result in faulty decompilation. This PR tries to bring changes that will ensure that operands are
converted with a proper method before usage.
> Try to fix issue #633

- CMakeLists.txt
- deps/yaramod/CMakeLists.txt
Current master will fail to build on 64-bit Linux machines due to looking for `libpog_fmt.a` at `external/src/yaramod-project-build/deps/pog/pog-install/lib/libpog_fmt.a` whereas, due to `include(GNUInstallDirs)` in the pog cmake config, the file will be located at `external/src/yaramod-project-build/deps/pog/pog-install/lib64/libpog_fmt.a`. This can be solved by adding the `include` statement (already present in `yaramod`) and using `CMAKE_INSTALL_LIBDIR` in the pog path.
> Allow building against pog on 64-bit Linux machines

- include/retdec/common/function.h
- include/retdec/llvmir2hll/config/config.h
- include/retdec/llvmir2hll/config/configs/json_config.h
- include/retdec/llvmir2hll/ir/module.h
- src/bin2llvmir/optimizations/dsm_generator/dsm_generator.cpp
- src/common/function.cpp
- src/llvmir2hll/config/configs/json_config.cpp
- src/llvmir2hll/hll/hll_writers/c_hll_writer.cpp
- src/llvmir2hll/ir/module.cpp
- src/serdes/function.cpp
- tests/llvmir2hll/config/config_mock.h
- tests/llvmir2hll/config/configs/json_config_tests.cpp
- tests/llvmir2hll/hll/hll_writers/hll_writer_tests.cpp
- tests/llvmir2hll/ir/module_tests.cpp
Hi in this PR I want to request and discuss a design change of function type in RetDec config.
Before this PR function type might have been one of the following:
- USER_DEFINED
- STATICALLY_LINKED
- DYNAMICALLY_LINKED
- SYSCALL
- IDIOM
The default function type that was generated for every function was
USER_DEFINED. This in my opinion is not right as we have to distinguish functions that
were provided by user through some kind of front-end and functions that
were automatically detected by decompiler. This is why I propose new type
- DECOMPILER_DEFINED.
A reason to distinguish these two function types is for example in parameter
analysis. When user specifies that the return type is integer, the decompiler
should not continue to do heuristics to detect return type. If an user
wants a …
> Request to provide new function type

- support/yara_patterns/tools/pe/x64/packers.yara
- support/yara_patterns/tools/pe/x86/packers.yara
The following changes ensure that previously undetected versions, and
hopefully future versions as well, are properly detected as Enigma.
See avast/retdec-regression-tests/pull/48 for tests.
> Improve the detection of Enigma protector (32-bit).

- support/yara_patterns/tools/pe/x86/installers.yara
Astrum InstallWizard is an installation software from Thraex Software and this PR aims at providing Fileinfo an ability to detect installation files, created using that software, correctly.
The tests for this enhancment were added [here](/avast/retdec-regression-tests/pull/53).
> Add detection support of Astrum InstallWizard.

- support/yara_patterns/tools/pe/x64/compilers.yara
- support/yara_patterns/tools/pe/x86/compilers.yara
AutoHotKey is a script compiler similar to AutoIt that aims at
automating and imitating the behaviour of an end user via series
of macros, hotkeys, and software automations.
> Add detection of AutoHotKey compiler.

- support/yara_patterns/tools/pe/x64/compilers.yara
- support/yara_patterns/tools/pe/x86/compilers.yara
AutoIT files compiled to binary using Aut2Exe are a regular PE file that
has its script embedded. This commit adds additional checks to catch and
detect the previously undetected version of the compiler.
The tests have been added [here](avast/retdec-regression-tests/pull/55)
> Improve the detection of AutoIT files compiled to binary.

- deps/yara/patch.cmake
Bug being fixed: https://github.com/VirusTotal/yara/pull/1289/files
This needs to be removed once the fix gets to RetDec.
> deps/yara/patch: patch YARA surces to fix bug in v4.0.1

- src/fileformat/file_format/pe/pe_format.cpp
* Overlapping of sections is not reported when the sections are of zero size
> * gu_idata and gu_rsrc section names are now considered packer sections

- src/fileformat/file_format/coff/coff_format.cpp
- src/fileformat/utils/format_detection.cpp
Do not parse COFF files at format detection stage - this could be slow if the file is big.
> fileformat/format_detection: use file magic to detect COFF files.

- include/retdec/pelib/DelayImportDirectory.h
- src/pelib/ImageLoader.cpp
* ImageLoader::stringLength() now stops properly on zero pages
> * Fixed high memory usage on samples with screwed up delayed imports

- src/cpdetect/heuristics/pe_heuristics.cpp
If a sample has corrupted PE header and as a result does not have any
sections, heuristic search for UPX packer will fail as it tries to
access the first section. To remedy this, we need to ensure the sections
exist before we access them.
Issue #821 
Test added [here](https://github.com/avast/retdec-regression-tests/pull/68)
> Fix crash on samples having corrupted PE header (#821)

- src/pelib/ImageLoader.cpp
> Fixed segfault on PE files whose IMAGE_FILE_HEADER is cut

- src/pelib/CoffSymbolTable.cpp
> Fix invalid memory read in PeLib::CoffSymbolTable::read() (#840)

- src/utils/CMakeLists.txt
Try to fix #842 by always linking against stdc++fs on Linux&GCC combo.
Notes:
* This might cause problems (later/now) on some system - if there is no stdc++fs known to GCC, linking against it will probably end up with error.
* We could use [`CMAKE_CXX_COMPILER_VERSION`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_VERSION.html) to check for GCC 7/8, but I didn't want to complicate it.
@xkubov Please take a look and merge if ok.
> utils: fix #842, always link stdc++fs if linux & gcc.

- support/yara_patterns/tools/pe/x86/installers.yara
Tests: https://github.com/avast/retdec-regression-tests/pull/74
> Lz installers install creator

- support/yara_patterns/tools/pe/x86/installers.yara
Tests: https://github.com/avast/retdec-regression-tests/pull/75
> Added YARA rules for Quick Batch installer

- support/yara_patterns/tools/pe/x86/installers.yara
Tests: https://github.com/avast/retdec-regression-tests/pull/76
> improved YARA rules for Wise installer

- support/yara_patterns/tools/pe/x86/installers.yara
Tests: https://github.com/avast/retdec-regression-tests/pull/77
> Added YARA rule for 'Xenocode Application Launcher'

- support/yara_patterns/tools/pe/x86/installers.yara
https://github.com/avast/retdec-regression-tests/pull/77
> Added YARA rules for SmartInstall Maker

- src/llvmir2hll/optimizer/optimizers/copy_propagation_optimizer.cpp
I came across a couple of infinite loops in copy_propagation_optimizer.cpp using the attach file.
[sslvpnd.zip](https://github.com/avast/retdec/files/5465739/sslvpnd.zip)
The sslvpnd binary should have a `sha256sum` of 856b68307d53d0f20f5c4a91aefc3146382e4e4210c758655d53135669642557 or you can find the binary embedded in this [firmware](https://www.cisco.com/c/en/us/support/routers/rv340-dual-gigabit-wan-vpn-router/model.html#~tab-downloads).
The infinite loop(s) can be reproduced by fetching retdec master from Github, compiling, and executing retdec-decompiler:
```
albinolobster@ubuntu:~/retdec/build$ retdec-decompiler ~/sslvpnd
```
After a couple of minutes, retdec drops into an infinite. The issue appears to be similar to [55d46b5f3a4a5ec038ab33331926a195c7f33250](https://github.com/ava …
> Fix infinite loops in copy propagation optimizer

- src/fileformat/file_format/pe/pe_format.cpp
While I was working on Signatures, I've noticed that usualPackerSections set is missing a comma in it's initializer, I think this is not intended?
> Fix missing comma in usualPackerSections initializer

- src/unpackertool/plugins/mpress/mpress.cpp
If the size of data is less than 0x1000 then we can possibly underflow
unsigned int and access unallocated data.
> Fixed possible access to unallocated memory in MPRESS unpacker

- include/retdec/pelib/ImageLoader.h
- include/retdec/pelib/PeLibAux.h
- src/pelib/ImageLoader.cpp
- src/pelib/ResourceDirectory.cpp
> Lz issue 907

- include/retdec/pelib/PeLibAux.h
- src/pelib/ResourceDirectory.cpp
> Fixed issue #911

- src/unpackertool/plugins/mpress/mpress.cpp
- src/unpackertool/plugins/mpress/mpress.h
- src/unpackertool/plugins/upx/pe/pe_upx_stub.cpp
After the commit 60ea783b558cce9b1f1a419df9c75be15588f3d2, we've had MPRESS unpacker bugged. Specifically the part which copied sections from packed PE into unpacked PE, which were not modified by packing process at all. This resulted in files unpacked by our `retdec-unpacker` to miss things like exports, resources and other things which are usually placed in their own sections (apart from imports which were properly reconstructed and unpacked code).
> unpacker/mpress: Properly copy non-packer related sections to the unpacked file

- scripts/retdec-fileinfo.py
If only `retdec-fileinfo` and `retdec-unpacker` are built and installed, then `retdec-archive-decompiler` is not installed. However in order to import `retdec-fileinfo.py`, it needs `retdec-archive-decompiler.py`. We'd like to have retdec fileinfo config handled better (through some JSONs) but this should at least solve it temporarily until better solution is made.
> Do not fail completely when retdec-archive-decompiler is not available

- include/retdec/fileformat/types/rich_header/rich_header.h
- src/fileformat/file_format/pe/pe_format.cpp
- src/fileformat/types/rich_header/rich_header.cpp
- src/fileinfo/file_information/file_information.cpp
- src/fileinfo/file_information/file_information.h
- src/fileinfo/file_information/file_information_types/rich_header.cpp
- src/fileinfo/file_information/file_information_types/rich_header.h
- src/fileinfo/file_presentation/json_presentation.cpp
- src/fileinfo/file_presentation/plain_presentation.cpp
I've added a calculation of decrypted (XORed) rich header hashes (crc32, md5, sha256) as mentioned in issue #621 . Not sure if all of them are wanted, probably MD5 only would be ok as used by VirusTotal: https://www.virustotal.com/gui/file/0ee196bb23f0eafe4f61d30bf6c676fd7365cb12ae66a6bde278851e91901ac1/details
> Calculate Rich header hash

- src/unpackertool/plugins/upx/upx_stub_signatures.cpp
There's a new stub for LZMA which doesn't contain NOP sleds to align 2 different pieces of unpacking stubs.
> Added new x86 PE signatures for LZMA UPX stub for UPX 3.94+

- src/fileformat/file_format/pe/authenticode/x509_certificate.cpp
Issue: [#954](https://github.com/avast/retdec/issues/954)
> Make X509 serial number parsing code compatible with YARA (#954)

- include/retdec/pelib/RichHeader.h
- src/fileformat/file_format/pe/pe_format.cpp
- src/pelib/RichHeader.cpp
This PR aims to fix #960 and to fix #965
The Rich header end is marked by the "Rich" marker somewhere between DOS header/stub and PE header. After the "Rich" follows the XOR key, when XORing the Rich header data, the start can be identified by "DanS" in ASCII and 3 null bytes for padding into a 16-byte paragraph. 
Current analysis decrypts the whole thing as it assumes there is no other data than Rich header there and then checks if there is "DanS" at the start. This doesn't behave correctly if there is any other "junk" data before the Rich header as it will decrypt it as well as is the case in #960 and just reports warning about wrong key because it didn't find the "DanS" at the start. I've changed the algorithm so it starts decrypting from the end ("Rich") to the top until it finds the …
> Fix the Rich header analysis algorithm

- src/pelib/ResourceDirectory.cpp
Aims to fix #959 
Sometimes the type name pointer points to (probably?) junk data, which results in a string with absurd length and content. A simple sanity check on the string length could solve this problem.
As in example `097a0f8b8c3f2b90f5360f27da5ef8e5a7406c6f211c8d3e56a1671933508bc1`. More details can be seen in the mentioned issue.
If this solution is "OK", I'll add a test case in regression test suite.
> Add sanity check for length of a PE resource type name

- include/retdec/fileformat/types/certificate_table/certificate.h
- src/fileformat/file_format/pe/authenticode/x509_certificate.cpp
- src/fileformat/file_format/pe/authenticode/x509_certificate.h
- src/fileformat/types/certificate_table/certificate.cpp
- src/fileinfo/file_presentation/json_presentation.cpp
Fixes #956 
I've added the subject/issuer oneline variant to the JSON output
> Add oneline subject/issuer to the output

- include/retdec/pelib/PeLibAux.h
- src/pelib/CoffSymbolTable.cpp
Fixes #957 
It seems there are 3 constants in the header:
- IMPORT_LIBRARY_MAX_LENGTH
- IMPORT_SYMBOL_MAX_LENGTH
- COFF_SYMBOL_NAME_MAX_LENGTH
I was wondering why isn't there a constant for exported symbols. It seems that for exported symbols there is no "sanity" length cap, it's capped by the default max value of the `read()` function (which is used to read the string from the image) which is 65535. I haven't seen any other MAX length constants in the pelib headers.
Based on the example binary I've raised those 3 constants to 256.
> Increased PE symbols MAX_LENGTH limits

- src/pelib/RichHeader.cpp
There was an undefined behavior because iterator pointing to begin() got decremented when the rich header parsing loop ends.
> Fix UB due to iterator reaching before begin() in rich header parsing 

- include/retdec/fileformat/types/resource_table/resource.h
Fixes #951 
Add virtual destructor for Resource class so the deletion of classes that inherit from Resource, when hidden behind pointer to the parent class, can be correctly freed.
> Fix PE resource memory leak due to missing virtual destructor.

- src/fileformat/file_format/pe/pe_format.cpp
Fixes #966 
I've added the necessary check for the Typelib custom attribute that the Parent points to the Assembly table to avoid detection of random GUIDs.
> Check for TypeLib parent relationship

- src/pelib/ImageLoader.cpp
Fixes #958 
The removal of all NULL chars in the pelib was intentional as in the comment: 
```
// Historically, PELIB copies the name of the section WITHOUT zero chars,
// even if the zero chars are in the middle. Aka ".text\0\0X" results in ".textX"
```
Not sure what was the reason, but based on the issue, I've changed the parsing to strip only the trailing zeroes.
> Change the section name parsing to only remove trailing zeroes

- include/retdec/fileformat/file_format/pe/pe_format.h
- include/retdec/fileformat/file_format/pe/pe_format_parser.h
- include/retdec/pelib/ImageLoader.h
- src/fileformat/file_format/pe/pe_format.cpp
- src/pelib/ComHeaderDirectory.cpp
- src/pelib/ImageLoader.cpp
- src/pelib/PeFile.cpp
.NET Edge cases are now handled properly
> Fixed Lz issue 967

- support/yara_patterns/tools/pe/x86/compilers.yara
The _ThunRTMain_ function is the one needed to startup a Visual Basic app (can be imported via ordinal), so if it's a VB executable is required to import it.
In addition, the use of ? wildcard may slow down the scanning.
> Modified Visual Basic's Yara rule

- support/yara_patterns/tools/pe/x64/compilers.yara
- support/yara_patterns/tools/pe/x86/compilers.yara
The [Ahk2Exe](https://github.com/AutoHotkey/Ahk2Exe/blob/d9ce9212bda26640811690257928b77424988be8/BinMod.ahk#L23) compiler allows to change the name of the section ">AUTOHOTKEY SCRIPT<" with an arbitrary string.
The proposed rule adds the check on some strings from the embedded interpreter.
Example of sample escaping the previous rule: [09e7d7d9312f8a02e70690a96015136bdeed63dd0f115ab1293091affeba8661](https://www.virustotal.com/gui/file/09e7d7d9312f8a02e70690a96015136bdeed63dd0f115ab1293091affeba8661)
> Modified AutoHotKey's Yara rule

- include/retdec/fileformat/types/certificate_table/certificate_table.h
- src/fileformat/file_format/pe/authenticode/pkcs7_signature.cpp
- src/fileformat/file_format/pe/pe_format.cpp
- src/fileinfo/file_presentation/json_presentation.cpp
- src/fileinfo/file_presentation/plain_presentation.cpp
Add a flag for each signature that represents if the signature and its signer were successfully verified (digest matches etc.) in the same manner as the previous implementation.
> Add signatureVerified flag for each signature

- include/retdec/fileformat/file_format/pe/pe_format.h
- include/retdec/fileformat/types/resource_table/resource.h
- include/retdec/pelib/ImageLoader.h
- src/cpdetect/heuristics/pe_heuristics.cpp
- src/fileformat/file_format/pe/pe_format.cpp
- src/fileformat/types/resource_table/resource.cpp
- src/fileinfo/file_information/file_information_types/resource_table/resource_table.cpp
- src/pelib/ImageLoader.cpp
Addresses partially #963 
Add check that the file offset of a Resource is actually somewhere inside section physical data
Sample that has such invalid offsets: 
`8a8154c36977c3f47a65c329a6dd93c58b8aff6050a4a748f4c610310daf0d8b`
If this fix is wanted, there are few things to consider:
- This means that offset 0 is considered bad. If 0 offsets could be valid (But I think they are not?) then the feedback about invalid offset should be changed
- For the offset 0 entries, the hash is calculated, which is unnecessary and could be misleading. This needs to be addressed too before possible merging.
> Add check that the resource file offset is valid

- include/retdec/fileformat/types/dotnet_headers/blob_stream.h
- include/retdec/fileformat/types/dotnet_headers/metadata_tables.h
- include/retdec/fileformat/types/dotnet_types/dotnet_class.h
- include/retdec/fileformat/types/dotnet_types/dotnet_type.h
- include/retdec/fileformat/types/dotnet_types/dotnet_type_reconstructor.h
- src/fileformat/file_format/pe/pe_format.cpp
- src/fileformat/types/dotnet_headers/blob_stream.cpp
- src/fileformat/types/dotnet_types/dotnet_class.cpp
- src/fileformat/types/dotnet_types/dotnet_type.cpp
- src/fileformat/types/dotnet_types/dotnet_type_reconstructor.cpp
This PR is fixing several .NET parsing differences and bugs:
> Fix of .NET analysis differences

- src/fileformat/file_format/pe/pe_format.cpp
Incompatible types `std::uint` and `unsigned long long` due to refactorization and incorrect merge conflict solution.
> Fix master not building due to conflicting types

- CMakeLists.txt
`PythonInterp` is old and deprecated module which may gave up on a system with multiple python installation like 2.7 and 3.x where `/usr/bin/python` is 2.7.
> Switch to using Python3 module to detect a python

- src/fileformat/types/dotnet_types/dotnet_type_reconstructor.cpp
Fix potential OOB read if passed data, to Signed/Unsigned dotnet decode function, is empty.
> Check if data is not empty in dotnet integer decoding functions

- deps/authenticode-parser/src/authenticode.c
- deps/authenticode-parser/src/certificate.c
- deps/authenticode-parser/src/countersignature.c
Here a minor changes in OpenSSL API.
Fixes: https://github.com/avast/retdec/issues/1040
> Update API for OpenSSL 3.0

- src/fileformat/file_format/pe/pe_format.cpp
When the resource tree doesn't have expected depth, we use different
path to load resources which didn't use loader but calculated offset
from RVA on it's own resulting in underflows on integers and completely
bogus offsets. Even though offsets are still kinda bogus, they make
sense and are within the file itself after this change.
Example file: f39f1ad9f97766618826d47c2d32529425e773659f5577fea06a82e21f13b064
> Use image loader when loading corrupted resources

- include/retdec/fileformat/types/export_table/export_table.h
- src/fileformat/file_format/pe/pe_format.cpp
- src/fileformat/types/export_table/export_table.cpp
- src/fileinfo/file_information/file_information.cpp
- src/fileinfo/file_information/file_information.h
- src/fileinfo/file_information/file_information_types/export_table.cpp
- src/fileinfo/file_information/file_information_types/export_table.h
- src/fileinfo/file_presentation/json_presentation.cpp
- src/fileinfo/file_presentation/plain_presentation.cpp
This PR adds `name` from the export directory table that represents the name of the DLL.
> Add dll name from export directory to output

- src/utils/memory.cpp
We can't limit memory on macOS. Before macOS 12 limitSystemMemoryOnPOSIX() does not actually do anything on macOS. Anyway, it just succeed, since macOS 12 it returns error and retdec can't start.
To be honest Apple can control memmory limit via so-called the ledger() system call which is private. An old verison which was opened to OpenSource (from 10.9-10.10?) using setrlimit() but at some point setrlimit() was broken and not ledger(). Probably at macOS 12 the setrlimit() was completley broken.
Because we haven't got any other choose just return true which haven't change anything.
See: https://github.com/avast/retdec/issues/379
Fixes: https://github.com/avast/retdec/issues/1045
> Never try to limit memory on macOS

- include/retdec/bin2llvmir/optimizations/param_return/param_return.h
- src/bin2llvmir/optimizations/param_return/param_return.cpp
Calls to dynamically-linked functions go through the procedure linkage
table (PLT).  RetDec turns a PLT entry into a function, say
malloc@plt, that appears to do nothing but call the external function,
say malloc (though the assembly code will do a jump rather than a
call). User code that logically wants to call malloc instead calls
malloc@plt (and sets up arguments as if calling malloc). The
malloc@plt code first jumps to the dynamic linker which modifies it so
that subsequent calls to malloc@plt will jump directly to malloc. We
say that malloc@plt wraps malloc.  The call to malloc in malloc@plt
will not have any arguments setup, so malloc will appear to have
no parameters or returns (unless that information is provided by
link-time-information, debug information, or name demangling), …
> Fix parameter and return types for dynamically called functions

- cmake/deps.cmake
- deps/capstone/patch.cmake
- include/retdec/bin2llvmir/optimizations/param_return/param_return.h
- include/retdec/common/range.h
- src/bin2llvmir/optimizations/param_return/param_return.cpp
- src/capstone2llvmir/powerpc/powerpc.cpp
- src/capstone2llvmir/x86/x86_init.cpp
- src/loader/loader/pe/pe_image.cpp
This is the latest released version of Capstone and the first Capstone release to support the endbr32 and endbr64 instructions. I was trying to add some new tests for RetDec, but although I can use an option to avoid producing the endbr instructions, the library has them so they end up in the produced binary. Thus if we want to add any new tests (which I do), we need to update to a newer Capstone.
> Upgrade to Capstone release 4.0.2 with patch

- src/bin2llvmir/optimizations/decoder/decoder.cpp
This case is for x86 32 bit compiled with GCC. Its PLT entries are in
sections .plt.sec or .plt.got. An entry is of the form:
jmp *offset(%ebx)
When this code is encountered register %ebx has been loaded with the
address of the start of the Global Offset Table (.got) section.
This change handles that case.
> Handle Procedure Linkage calls for 32bit x86 from gcc

- LICENSE-THIRD-PARTY
- cmake/options.cmake
- deps/CMakeLists.txt
- deps/stb/CMakeLists.txt
- deps/stb/include/stb/stb_image.h
- deps/stb/retdec-stb-config.cmake
- deps/stb/stb_image.c
- include/retdec/fileformat/types/resource_table/bitmap_image.h
- src/fileformat/CMakeLists.txt
- src/fileformat/types/resource_table/bitmap_image.cpp
- src/fileformat/types/resource_table/resource_table.cpp
I've integrated https://github.com/nothings/stb `stb_image.h` to add loading of PNG icons for perceptual hash calculation. I've flipped the PNG image upside down, as the existing DIB format is stored upside down, and I wanted to align with the current implementation.
I've handcrafted some test samples to the appropriate repository with mention of this PR. I took a sample with PNG Icon, extracted it in a different resolution, converted it to DIB format, and put it inside another file. Then I test if the perceptual hash of both file match.
> Add ability to process PNG icons for perceptual hash calculation

- include/retdec/llvmir2hll/hll/hll_writer.h
- src/llvmir2hll/hll/hll_writer.cpp
When the program involves dynamically-linked functions like _Znwj
(operator new) that return a pointer, it is necessary to have
prototypes for them, since otherwise they will be implicitly deduced
to return "int" which cannnot be dereferenced.
Previously RetDec was emitting comments telling which functions were
dynamically linked. This change moves them up before the functions are
emitted and instead emits prototypes for the functions. However,
RetDec also inserts includes of headers for functions with known
headers. So this change does not emit prototypes for functions with headers as that
would be redundant.  As a result, some dynamically-linked functions
that used to show in the comments no longer appear as the included
header will declare them.
The section header comment for …
> Add prototypes for dynamically-linked functions without headers

- src/fileinfo/file_information/file_information.cpp
- src/fileinfo/file_information/file_information.h
- src/fileinfo/file_presentation/json_presentation.cpp
- src/fileinfo/file_presentation/json_presentation.h
- src/fileinfo/file_presentation/plain_presentation.cpp
- src/fileinfo/file_presentation/plain_presentation.h
- src/fileinfo/fileinfo.cpp
This adds printing of the time of an analysis into both plain and JSON output of `retdec-fileinfo`. It only does it when `--analysis-time` command line options is used if anyone ever relied on the fact that the output of `retdec-fileinfo` is always the same.
> Add printing of analysis time to retdec-fileinfo output

- include/retdec/pelib/ImageLoader.h
- src/pelib/ImageLoader.cpp
There are certain samples where page index might go beyond available pages when trying to load them which will be prevented with this patch.
> Added sanity check for page index when loading pages from broken samples

- src/bin2llvmir/optimizations/decoder/decoder_ranges.cpp
> Fix removeZeroSequences

- deps/yara/CMakeLists.txt
This is another approach to remove hardocoded call of `make` to build `yara`. This approach uses the same `make` by default but introduces `YARA_MAKE_PROGRAM` option which can be used to specify a path to `gmake` for example.
Thus, when CMake produces a set of makefile, it reuses `CMAKE_MAKE_PROGRAM` to respect a global `-jXXX` option.
> Allow to configure `yara`'s make tool

- src/bin2llvmir/optimizations/decoder/decoder.cpp
Reference: https://github.com/avast/retdec/issues/638
> Try to fix issue #638

- deps/yara/CMakeLists.txt
option() is intended for boolean variables only. This could break the build e.g. with cmake 3.23.4 on macOS where the passed default "make" was interpreted as false and "OFF" was instead passed to the yara configure.
The correct way is to use an explicit CACHE variable here.
> Make YARA_MAKE_PROGRAM a FILEPATH (string) cache var

- src/fileformat/file_format/elf/elf_format.cpp
- src/fileformat/types/import_table/elf_import_table.cpp
- src/fileformat/types/import_table/import_table.cpp
These kind of hashes are always provided as upper-case (for example on VirusTotal). We are the only one providing them in lower-case and we are doing it deliberately. I suggest not to do it and provide them as-is and that is uppercase.
> Do not transform TLSH and provide it as-is (uppercase)

- .github/workflows/macOS/install-deps.sh
- .github/workflows/retdec-ci.yml
MacOS CI workflow is failing because python3.7 is deprecated and the build fails.
The doxygen build also fails due to deprecated github CI ubuntu version, it was changed to ubuntu-latest so it won't happen again.
> MacOS workflow fix - Use new version of python and ubuntu that is not deprecated

- .github/workflows/macOS/install-deps.sh
- .github/workflows/retdec-ci.yml
- src/fileformat/file_format/pe/pe_format.cpp
When reading  strings from String stream of .NET binaries, there was no check, if the reading was actually succesfull (there is something to read in the file on that offset).
The string parsing is set to stop when it fails to read some string as they are read consecutively, so if offset X is out of bounds, X+1 should be too and there should be no reason to read further.
> Fix .NET parser trying to read strings from String stream when out-of-bounds of the file

- src/fileformat/file_format/pe/pe_format.cpp
To unify .NET parsing in YARA and Retdec, the same kind of check has to be used before trying to parse binary as .NET (to avoid malformed binaries). The checking logic was already implemented by me a year ago, but it was for some reason used only in compiler detection heuristics and not during .NET parsing.
> Use isDotnet check before parsing binary as .NET

- src/bin2llvmir/optimizations/decoder/decoder_init.cpp
- src/bin2llvmir/optimizations/idioms/idioms_abstract.cpp
- src/config/parameters.cpp
- src/cpdetect/heuristics/heuristics.cpp
- src/fileinfo/file_information/file_information.cpp
Remove empty return types from doxygen comments to fix warnings.
This will be fix below warnings and make GitHub Actions doc test pass.
```
$ cat build/doc/doxygen/doxygen.log
/Users/takano32/GitHub/retdec/src/bin2llvmir/optimizations/decoder/decoder_init.cpp:22: warning: found documented return type for retdec::bin2llvmir::Decoder::initTranslator that does not return anything
/Users/takano32/GitHub/retdec/src/bin2llvmir/optimizations/idioms/idioms_abstract.cpp:43: warning: found documented return type for retdec::bin2llvmir::IdiomsAbstract::eraseInstFromBasicBlock that does not return anything
/Users/takano32/GitHub/retdec/src/config/parameters.cpp:478: warning: found documented return type for retdec::config::Parameters::serialize that does not return anything …
```
> Fix warnings in `make doc`

- .github/workflows/retdec-ci.yml
Document generated successfly if `make doc` exit code equals `0`.
So, ignoring warnigs is reasonable in GitHub Actions, I think.
> [GitHub Actions] ignore doxygen wranings

- include/retdec/fileformat/types/import_table/import.h
- include/retdec/fileformat/types/import_table/import_table.h
- src/fileformat/file_format/elf/elf_format.cpp
- src/fileformat/types/import_table/import.cpp
- src/fileformat/types/import_table/import_table.cpp
* Problematic file `6dae046fe2268eba225be5916013b7799ba042c7ca87cd49cda77ae59a34d29f`.
* Objectdump and readelf say there are no symbols, but we found ~50k of them.
* First ~30k looks ok, so its not all garbage.
* In the next ~20k, there are a lot of (but not all) same symbols with empty name, zero section index, zero address, etc.
* However, we have relocations for these values anyway, and a lot of them (~170k).
* So, we end up with ~20K same symbols each with ~170K relocations -> 3.4B Imports.
* The problem is, that from program's PoV, nothing is obviously wrong. The addresses are valid in the binary, relocation are into valid sections/segments, etc.
* We could make some heuristic to fix this concrete situation, e.g. cap that multiplication result, trim it down/skip it for empty-named …
> fileformat/elf: Prevent creation of duplicate imports while parsing
